parameters:
#    unicornum_metalum_front.example.class: UnicornumMetalum\FrontBundle\Example

services:
#    unicornum_metalum_front.example:
#        class: %unicornum_metalum_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
