parameters:
#    unicornum_metalum_admin.example.class: UnicornumMetalum\AdminBundle\Example

services:
#    unicornum_metalum_admin.example:
#        class: %unicornum_metalum_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    unicornum_metalum_admin.admin.review:
        class: UnicornumMetalum\AdminBundle\Admin\ReviewAdmin
        arguments: [~, UnicornumMetalum\EntityBundle\Entity\Review, UnicornumMetalumAdminBundle:ReviewAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Review}

    unicornum_metalum_admin.admin.category:
        class: UnicornumMetalum\AdminBundle\Admin\CategoryAdmin
        arguments: [~, UnicornumMetalum\EntityBundle\Entity\Category, UnicornumMetalumAdminBundle:CategoryAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Category}

    unicornum_metalum_admin.admin.tag:
        class: UnicornumMetalum\AdminBundle\Admin\TagAdmin
        arguments: [~, UnicornumMetalum\EntityBundle\Entity\Tag, UnicornumMetalumAdminBundle:TagAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Tag}

    unicornum_metalum_admin.admin.comment:
        class: UnicornumMetalum\AdminBundle\Admin\CommentAdmin
        arguments: [~, UnicornumMetalum\EntityBundle\Entity\Comment, UnicornumMetalumAdminBundle:CommentAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Comment}
